url: "https://www.jessiekrikken.nl"

title: Jessie Krikken
search_enabled: false

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
  ]

remote_theme: pmarsceill/just-the-docs
